sudo: required
services:
  docker

before_install:
  - docker build -t vishal1201/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true vishal1201/react-test npm run test -- --coverage

after_success:
  - docker build -t vishal1201/multi-client ./client
  - docker build -t vishal1201/multi-nginx ./nginx
  - docker build -t vishal1201/multi-server ./server
  - docker build -t vishal1201/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --passwords-stdin
  - docker push vishal1201/multi-client
  - docker push vishal1201/multi-nginx
  - docker push vishal1201/multi-server
  - docker push vishal1201/multi-worker